version: "3.8"

services:
  api:
    container_name: temperature_system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default: